name: Report Stream Issue Report
description: Report an issue with Report Stream
title: "[Type a short name for your issue here]: "
labels: ["issue", "triage"]
assignees: ["Herman Cordero","Adrian Brewster"]
  
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this Report Stream report!
  - type: input
    id: name
    attributes:
      label: Contact Name
      description: Name of the person submitting this report
      placeholder: Mr. John Administrator
    validations:
      required: true
  - type: input
    id: organization
    attributes:
      label: Submitting Organization
      description: Name of the organization submitting this report
      placeholder: Louisiana Department of Health
    validations:
      required: true
  - type: input
    id: email
    attributes:
      label: Contact Email
      description: How do we contact you?
      placeholder: ex. youremail@example.com
    validations:
      required: true
  - type: textarea
    id: issue_description
    attributes:
      label: Issue description
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "not what I expected!"
    validations:
      required: true
  - type: textarea
    id: expected behaviour
    attributes:
      label: Issue description
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "not what I expected!"
    validations:
      required: true

  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of Report Stream?
      options:
        - HL7
        - CSV Uploader
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
